config/routes.rb
Rails.application.routes.draw do

  resources :testimonials
  
  mount Ckeditor::Engine => '/ckeditor'

  resources :permissions

  resources :sessions

  resources :password_resets

  resources :users

  resources :posts do 
    resources :comments
  end

  get '/about' => 'pages#about'

  get '/contact' => 'pages#contact'

  root 'pages#index'

  get '/blog' => 'posts#index'

  get '/register' => 'users#new'

  get '/profile/:id' => 'users#show'

  get '/login' => 'sessions#new'

  get 'tags/:tag', to: 'posts#tag', as: :tag

  resources :categories

  # admin
  namespace :madmin do
    resources :dashboard
    get '', to: 'dashboard#index', as: '/'

    resources :posts do
      get ":category_id", action: :index, on: :collection
    end

  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/madmin.rb
module Madmin
  def self.table_name_prefix
    'madmin_'
  end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
	attr_accessible :user_id, :name, :content, :status, :category_id, :picture, :tag_list
	has_many :taggings
	has_many :tags, through: :taggings
	has_many :comments

	validates :name, presence: true, allow_blank: false
	validates :category_id, presence: true, allow_blank: false
	validates :picture, presence: true, allow_blank: false
	#validates :tag_list, presence: true, allow_blank: false
	validates :content, presence: true, allow_blank: false

	# has_attached_file :image
 #    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  	mount_uploader :picture, ImageUploader


  	def self.tagged_with(name)
	  Tag.find_by_name!(name).posts
	end

	def self.tag_counts
	    Tag.select("tags.*, count(taggings.tag_id) as count").
	    joins(:taggings).group("taggings.tag_id")

	    #DataMapper.repository.adapter.select('select tags.*, t.count from tags inner join (select taggings.tag_id, count(taggings.tag_id) as count from taggings group by taggings.tag_id) t where tags.id = t.tag_id')
	end

	def tag_list
	  tags.map(&:name).join(", ")
	end

	def tag_list=(names)
	  self.tags = names.split(",").map do |n|
	    Tag.where(name: n.strip).first_or_create!
	  end
	end

	def self.search(search)
		  where("name LIKE ?", "%#{search}%") 
		  where("content LIKE ?", "%#{search}%")
	end
end

app/models/session.rb
class Session < ActiveRecord::Base
	# validates :uname, :presence => true, :uniqueness => true
	# validates :pword, :presence => true, :uniqueness => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	attr_accessible :name
	has_many :taggings
	has_many :posts, through: :taggings

	def self.tag_counts
	  Tag.select("tags.*, count(taggings.tag_id) as count").
	    joins(:taggings).group("taggings.tag_id")
	end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	  #attr_accessor :password
    #has_secure_password
	  has_many :posts
    has_many :reviews
    has_many :comments
    before_save :encrypt_password
    after_save :clear_password
    #before_create { generate_token(:auth_token) }

    has_attached_file :avatar
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

    #attr_accessible :email, :password, :password_confirmation

    #validates_presence_of :password, :on => :create

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :first_name, :length => { :in => 3..20 }
    validates :last_name, :length => { :in => 3..20 }
    validates :uname, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
          
    validates :pword, :confirmation => true #password_confirmation attr
    validates_length_of :pword, :in => 6..20, :on => :create


    def encrypt_password
      if pword.present?
        self.salt = BCrypt::Engine.generate_salt
        self.pword= BCrypt::Engine.hash_secret(pword, salt)
      end
    end
    
    def clear_password
      self.pword = nil
    end

    def match_password(pword="")
        pword == BCrypt::Engine.hash_secret(pword, salt)
    end

    def self.authenticate(username="", login_password="")
      user = User.find_by_uname(username)
      
      if user && user.match_password(login_password)
        return user
      else
        return false
      end
    end  

    def match_password(login_password="")
      pword == BCrypt::Engine.hash_secret(login_password, salt)
    end

    def send_password_reset
      generate_token(:password_reset_token)
      self.password_reset_sent_at = Time.zone.now
      save!
      UserMailer.password_reset(self).deliver
    end

    def generate_token(column)
      begin
        self[column] = SecureRandom.urlsafe_base64
      end while User.exists?(column => self[column])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	layout 'layouts/index', only: [:index]

	def index
	end

	def about
	end

	def contact
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def tag_cloud(tags, classes)
	    max = 0
	    tags.each do |t|
	      if t.count.to_i > max
	        max = t.count.to_i
	      end 
	    end
	    tags.each do |tag|
	      index = tag.count.to_f / max * (classes.size - 1)
	      yield(tag, classes[index.round])
	    end
	end 
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def tag_links(tags)
	  tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    	session[:user_id] = user.id
  	end

	# Returns the current logged-in user (if any).
	def current_user
	    @current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin/_footer.html.erb
<footer><p>Copyright 2016 &copy MBlog by hklog</p></footer>

app/views/layouts/admin/_header.html.erb
<header class="container-fluid">
	<div class="col-md-4">
		<h1><%= link_to 'MBlog', madmin_dashboard_index_path %></h1>
	</div>

	<div class="col-md-8">
		<h3><%= session[:user_name] %></h3>
		<%= link_to 'Logout', session_path(session), method: :delete %>
	</div>
</header>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuickShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<section class="layout-admin">
	<%= render 'layouts/admin/header' %>

	<section class="container-fluid admin-main-content">
		<div class="col-md-3 admin-sider">
			<ul>
				<li><li><%= link_to 'Posts Manager', madmin_posts_path %></li></li>
				<li><a href="#">Users Manager</a></li>
				<li><a href="#">Pages Manager</a></li>
			</ul>
		</div>

		<div class="col-md-9 admin-content">
			<%= yield %>
		</div>
			
	</section>

	<%= render 'layouts/admin/footer' %>
</section>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render '/layouts/partials/header' %>
<section class="container-fluid wrapper">
	<%= yield %>
</section>
<%= render '/layouts/partials/footer' %>
</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render '/layouts/partials/header' %>

<section class="container-fluid wrapper">
	<div class="container slideshow">
			<div class="col-md-8 slide-details">
				<%= render '/layouts/partials/slideshow' %>
			</div>
			<div class="col-md-4 slide-post-content">
				<div class="slide-post-content-1">
					<h3 class="head">Random Posts</h3>
					<% Post.all.limit(5).each do |post| %>
						<div class="col-md-12 post-details">
							<div class="body-img">
		                        <% if post.picture? %>
		                          <%= image_tag post.picture_url() %>
		                        <% else %>
		                          <%= image_tag ("mblog.jpg") %>
		                        <% end %>
		                    </div>
		                    <div class="body-content">
		                        <div class="hk-posts-content">
		                            <!-- <i class="fa fa-quote-left"></i> -->
		                            <h3><%= link_to post.name, post %></h3>
		                            <p class="meta-data"><span>By </span><%= post.user.uname %></p>
		                            <!-- <i class="fa fa-quote-right"></i> -->
		                        </div>
		                    </div>
						</div>
					<% end %>
				</div>
			</div>
	</div>

	<div class="container posts-index">
		<%= render '/layouts/partials/posts_index' %>
	</div>

	<!-- <div class="container background">
		<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.</p>
	</div> -->

</section>
<%= render '/layouts/partials/footer' %>

</body>
</html>

app/views/layouts/partials/_footer.html.erb
<footer class="container-fluid footer">
	<div class="footer-top">
		<div class="col-md-3" >
			<h3>DOWNLOAD</h3>
			<ul>
				<li><a href="#">Installing Ruby on rails</a></li>
				<li><a href="#">Documentation</a></li>
				<li><a href="#">API</a></li>
				<li><a href="#">Tutorial</a></li>
				<li><a href="#">Sample</a></li>
			</ul>
		</div>
		<div class="col-md-3" >
			<h3>COMMUNITY</h3>
			<ul>
				<li><a href="#">Forum</a></li>
				<li><a href="#">GitHub</a></li>
				<li><a href="#">Issue Tracker</a></li>
				<li><a href="#">Stack Overflow</a></li>
				<li><a href="#">Testimonials</a></li>
			</ul>
		</div>
		<div class="col-md-3" >
			<h3>ABOUT</h3>
			<ul>
				<li><a href="#">Blog</a></li>
				<li><a href="#">About</a></li>
				<li><a href="#">Team</a></li>
				<li><a href="#">Roadmap</a></li>
				<li><a href="#">Donate</a></li>
			</ul>
		</div>
		<div class="col-md-3">
			<h3>MBlog</h3>
			<p>Found a typo or an error? Want to improve this document? The documentation sources are available on Github Need support or have questions? Check our Forum Ruby on rails Framework is released under the new BSD license. Except where otherwise noted, content on this site is licensed under the Creative Commons Attribution 3.0 License.</p>
		</div>
	</div>
	<div class="copy-right col-md-12">
		<p>MBlog © <%= Time.now.year %> by hklog </p>
	</div>
</footer>

app/views/layouts/partials/_header.html.erb
<header class="header container-fluid">
	<div class="row">
		<div class="col-md-12 header-top">
			<div class="login">
				<% if( session[:user_id] || cookies[:user_id] ) %>
						
					<a class="login-avatar" href="/profile/<%= session[:user_id] %>">Profile</a> | 
					<%= link_to 'Logout', session_path(session), method: :delete %>
					<% else %>
						<a href="/login">Login</a> | 
						<a href="/register">Register</a>
				<% end %>
			</div>
		</div>
		<div class="col-md-12 header-bottom">
			<div class="col-md-3 logo">
				<h1><a href="<%= root_path %>">MBlog</a></h1>
			</div>
			<div class="col-md-6 menu">
				<nav class="menu-nav">
					<ul>
						<li><a href="/">Home</a></li>
						<li><a href="/blog">Blog</a>
							<ul>
								<% Category.all.each do | cat | %>
									<li><%= link_to cat.name, cat %></li>
									
								<% end %>
							</ul>
						</li>
						<li><a href="/about">About us</a></li>
						<li><a href="/contact">Contact us</a></li>
					</ul>
				</nav>
			</div>
			<div class="col-md-3 search">
				<% form_for :search, :url => { :controller => 'posts', :action => 'index' } do %>
				  <p>
				    <%= text_field_tag :search, params[:search], :placeholder => 'Input Text' %>
				    <%= submit_tag "Search", :name => nil %>
				  </p>
				<% end %>
			</div>
		</div>
	</div>
</header>

<script type="text/javascript">
	$('.login-profile').hide();
	$('.login-avatar').click(function(){
	    $('.login-profile').slideToggle('slow');
	});
</script>

app/views/layouts/partials/_posts.html.erb
<% 
	i = 0
	a = []
%>

<% Post.all.limit(13).each do |post| %>
	<% i = i + 1 %>
	<% a[i] = post %>
<% end %>
<div class="grid-view">
	<div class="grid-sizer"></div>
  	<div class="grid-item grid-item--width2">
  		<h3><%= a[1].name %></h3>
  		<p><%= raw a[1].content.first(200) %></p>
  		
  	</div>
  	<div class="grid-item grid-item--height2">
  		<% if a[3].picture? %>
            <%= image_tag post.picture_url() %>
        <% else %>
              <%= image_tag ("mblog.jpg") %>
       <% end %>                       
	</div>
  	<div class="grid-item grid-item--width2 grid-item--height2"><%= a[4].name %></div>
  	<div class="grid-item grid-item--width2 grid-item--height2"><%= a[5].name %></div>
  	<div class="grid-item grid-item--width2"><%= a[6].name %></div>
  	<div class="grid-item grid-item--width2"><%= a[7].name %></div>
  	<div class="grid-item grid-item--height2"><%= a[8].name %></div>
  	<div class="grid-item"><%= a[9].name %></div>
  	<div class="grid-item grid-item--width2"><%= a[10].name %></div>
  	<div class="grid-item grid-item--height2"><%= a[11].name %></div>
  	<div class="grid-item"><%= a[12].name %></div>
  	<div class="grid-item"><%= a[13].name %></div>
</div>

app/views/layouts/partials/_posts_index.html.erb
<div class="posts">
  <% Post.order('created_at DESC').limit(16).each do |post| %>
        <div class="col-md-3 col-sm-6 col-xs-12 posts-details">
          <div class="posts-details-1">
            <div class="img">
              <% if post.picture? %>
                  <%= link_to (image_tag post.picture_url()), post %>
                <% else %>
                  <%= link_to (image_tag ("mblog.jpg")), post %>
              <% end %>
            </div>

            <div class="content">
              <h3><%= link_to post.name.first(40), post %></h3>
              <p><span>Posted at <%= time_ago_in_words(post.created_at) %></span></p>
              <p><%= raw post.content.first(110) %></p>
              <p class="readmore"><%= link_to 'Read More', post %></p>
            </div>
          </div>
            
        </div>
  <% end %>
</div>

app/views/layouts/partials/_posts_test.html.erb
<% 
	i = 0
	a = []
%>

<% Post.all.limit(13).each do |post| %>
	<% i = i + 1 %>
	<% a[i] = post %>
<% end %>
<div class="grid-posts">
	<div class="col-md-6 grid-posts-nav">
    <div class="content">
      <div class="img-left">
        <% if a[1].picture? %>
            <%= image_tag post.picture_url() %>
        <% else %>
              <%= image_tag ("mblog.jpg") %>
        <% end %>   
      </div>
      <div class="content-right">
    		<h3><%= a[1].name %></h3>
    		<p><%= raw a[1].content.first(100) %></p>
      </div>
    </div>		
	</div>
	<div class="col-md-3 grid-posts-1">
    <div class="content">
      <div class="img">
    		<% if a[2].picture? %>
              <%= image_tag post.picture_url() %>
          <% else %>
                <%= image_tag ("mblog.jpg") %>
         <% end %>
      </div>
      <div class="details">
        <h3><%= a[2].name %></h3>
        <p><%= raw a[2].content.first(100) %></p>
      </div>
    </div>                     
	</div>

  <div class="col-md-3 grid-posts-1">
    <div class="content">
      <div class="details">
        <h3><%= a[3].name %></h3>
        <p><%= raw a[3].content.first(100) %></p>
      </div>   
      <div class="img">
        <% if a[3].picture? %>
              <%= image_tag post.picture_url() %>
          <% else %>
                <%= image_tag ("mblog.jpg") %>
         <% end %>
      </div>
      
    </div>                    
  </div>

  <div class="col-md-6 grid-posts-nav">
    <div class="content">
      <div class="img-right">
        <% if a[4].picture? %>
            <%= image_tag post.picture_url() %>
        <% else %>
              <%= image_tag ("mblog.jpg") %>
        <% end %>   
      </div>
      <div class="content-left">
        <h3><%= a[4].name %></h3>
        <p><%= raw a[4].content.first(100) %></p>
      </div>
    </div>    
  </div>

  <div class="col-md-6">
    <h3><%= a[5].name %></h3>
    <p><%= raw a[5].content.first(100) %></p>
  </div>

  <div class="col-md-3">
    <% if a[6].picture? %>
          <%= image_tag post.picture_url() %>
      <% else %>
            <%= image_tag ("mblog.jpg") %>
     <% end %>                       
  </div>
</div>

app/views/layouts/partials/_slideshow.html.erb
<div class="slideshow">  
  <div class="slideshow-detail">
    <div class="hk-slick-wrap">
    <div class="hk-posts-default">
        <div class="hk-posts-wrap">
            <% Post.all.limit(10).order('created_at DESC').each do | post | %>
                <div>
                    <div class="hk-posts-body">
                      <div class="body-img">
                        <% if post.picture? %>
                          <%= image_tag post.picture_url() %>
                        <% else %>
                          <%= image_tag ("mblog.jpg") %>
                        <% end %>

                      </div>
                      <div class="body-content">
                        <div class="hk-posts-content">
                            <!-- <i class="fa fa-quote-left"></i> -->
                            <h3><%= link_to post.name, post %></h3>
                            <%= raw post.content.first(100) %>
                            <!-- <i class="fa fa-quote-right"></i> -->
                        </div>
                      </div>
                    </div>
                </div>
            <% end %>
        </div>

        <div class="hk-posts-sider-nav">
            <% Post.all.limit(10).order('created_at DESC').each do | post | %>
                <div class="nav-imgs">
                  <% if post.picture? %>
                    <%= image_tag post.picture_url() %>
                  <% else %>
                    <%= image_tag ("mblog.jpg") %>
                  <% end %>
                  <div class="hover"></div>
                </div>
            <% end %>
        </div>
        
      </div>
    </div>
  </div>
</div>


      

app/views/layouts/partials/_testimonials.html.erb
<div class="mb-testimonials">
	<h3 class="head">Testimonials</h3>
	<div id="owl-demo" class="owl-carousel">
	    <% Testimonial.all.limit(3).each do | testi | %>

	        <div class="item">
	          	<% if testi.image? %>
	              <%= image_tag testi.image_url() %>
	            <% else %>
	              <%= image_tag ("mblog.jpg") %>
	            <% end %>
	          	<div class="item-detail">
	          		<h4><%= testi.name %></h4>
	          		<h5><%= testi.website %></h5>
	          		<p><%= raw testi.content %></p>
	          	</div>
	        </div>
	    <% end %>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {

  $("#owl-demo").owlCarousel({

      navigation : true, // Show next and prev buttons
      slideSpeed : 300,
      paginationSpeed : 400,
      //singleItem:true,

      // "singleItem:true" is a shortcut for:
      items : 3
      // itemsDesktop : false,
      // itemsDesktopSmall : false,
      // itemsTablet: false,
      // itemsMobile : false

  });
});
</script>

app/views/layouts/post.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render '/layouts/partials/header' %>
<section class="container wrapper">
	<div class="col-md-9">
		<%= yield %>	
	</div>

	<div class="col-md-3">
		<div class="post-sidebar">
			<h3 class="head">Category</h3>
			<ul>
				<% Category.all.each do | cat | %>
					<li>
						<i class="fa fa-folder-open-o" aria-hidden="true"></i>
						<%= link_to cat.name, cat %>
					</li>
				<% end %>
			</ul>
		</div>

		<div class="post-sidebar">
			<h3 class="head">Related Posts</h3>
			<ul>
				<% Post.all.order('created_at DESC').limit(10).each do | post | %>
					<li class="li-rpost">
						<%= link_to post.name, post %>
					</li>
				<% end %>
			</ul>
		</div>

		<div class="post-sidebar">
			<h3 class="head">Tags Cloud</h3>
			<div class="tags">
				<% tag_cloud Post.tag_counts, %w{css1 css2 css3 css4} do |tag, css_class| %>
				    <%= link_to tag.name, tag_path(tag.name), class: 'tag-cloud' %>
				<% end %>
			</div>
		</div>
		
	</div>
</section>
<%= render '/layouts/partials/footer' %>

</body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render '/layouts/partials/header' %>
<section class="container wrapper">
	<div class="col-md-9">
		<%= yield %>	
	</div>

	<div class="col-md-3">
		<div class="post-sidebar">
			<h3 class="head">Category</h3>
			<ul>
				<% Category.all.each do | cat | %>
					<li>
						<i class="fa fa-folder-open-o" aria-hidden="true"></i>
						<%= link_to cat.name, cat %>
					</li>
				<% end %>
			</ul>
		</div>

		<div class="post-sidebar">
			<h3 class="head">Related Posts</h3>
			<ul>
				<% Post.all.order('created_at DESC').limit(10).each do | post | %>
					<li class="li-rpost">
						<%= link_to post.name, post %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>

</section>
<%= render '/layouts/partials/footer' %>

</body>
</html>